# Generated by Django 3.1.1 on 2021-01-03 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201231_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='discription',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='200'),
            preserve_default=False,
        ),
    ]
